# Generated by Django 6.0.1 on 2026-01-24 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveStream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('embed_url', models.URLField(blank=True, null=True)),
                ('is_live', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('live', 'Live'), ('offline', 'Offline'), ('error', 'Error')], default='offline', max_length=50)),
                ('date', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=50)),
                ('time', models.CharField(max_length=50)),
                ('timezone', models.CharField(default='America/New_York', max_length=50)),
                ('type', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
