# Generated by Django 5.2 on 2026-01-24 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_livestream_serviceschedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='GivingOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('icon_name', models.CharField(help_text='FontAwesome icon name e.g. FaMoneyBillWave', max_length=100)),
                ('account_name', models.CharField(blank=True, max_length=200)),
                ('account_number', models.CharField(blank=True, max_length=200)),
                ('bank_name', models.CharField(blank=True, max_length=200)),
                ('mobile_number', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'title'],
            },
        ),
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='events/'),
        ),
        migrations.AddField(
            model_name='ministry',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='ministries/'),
        ),
        migrations.AddField(
            model_name='sermon',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='sermons/'),
        ),
    ]
