# Generated by Django 5.2 on 2026-01-27 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_leadership_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChurchInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='New Gate Chapel', max_length=200)),
                ('hero_subtitle', models.CharField(default='Welcome Home', max_length=200)),
                ('hero_title', models.CharField(default='Welcome to New Gate Chapel', max_length=500)),
                ('hero_description', models.TextField(default="A place of worship, community, and spiritual growth. Join us as we journey together in faith and discover God's purpose for our lives.")),
                ('about_story', models.TextField(default='New Gate Chapel was founded with a vision...')),
                ('about_mission', models.TextField(default='To glorify God by making disciples of Jesus Christ who love God, love others, and serve the world.')),
                ('about_vision', models.TextField(default='A community where every person experiences the transforming love of Christ and discovers their God-given purpose.')),
                ('address', models.CharField(blank=True, max_length=500)),
                ('phone', models.CharField(blank=True, max_length=100)),
                ('email', models.CharField(blank=True, max_length=200)),
                ('facebook_url', models.URLField(blank=True, null=True)),
                ('instagram_url', models.URLField(blank=True, null=True)),
                ('youtube_url', models.URLField(blank=True, null=True)),
                ('twitter_url', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Church Information',
                'verbose_name_plural': 'Church Information',
            },
        ),
        migrations.CreateModel(
            name='HomeFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('icon_name', models.CharField(default='FaHeart', help_text='FontAwesome icon name', max_length=100)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'title'],
            },
        ),
    ]
