# Generated by Django 5.2 on 2026-01-29 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_churchinfo_homefeature'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadership',
            name='x_url',
            field=models.URLField(blank=True, help_text='X (Twitter) profile URL', null=True),
        ),
        migrations.AlterField(
            model_name='livestream',
            name='embed_url',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
