# Generated by Django 5.2 on 2026-01-29 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_leadership_x_url_alter_livestream_embed_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='churchinfo',
            name='giving_intro',
            field=models.TextField(default='Your generosity enables us to reach our community, support missions, and continue the work of God in our city.'),
        ),
        migrations.AddField(
            model_name='churchinfo',
            name='giving_verses',
            field=models.JSONField(blank=True, default=list, help_text='List of inspirational verses for the giving page'),
        ),
        migrations.AddField(
            model_name='givingoption',
            name='color',
            field=models.CharField(default='#3b82f6', max_length=50),
        ),
    ]
