# Generated by Django 6.0.1 on 2026-01-31 17:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_contactmessage_replied_at_contactmessage_reply_text'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='ministry',
            options={'ordering': ['order', 'title'], 'verbose_name_plural': 'Ministries'},
        ),
        migrations.AlterModelOptions(
            name='sermon',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='serviceschedule',
            options={'ordering': ['order', 'day']},
        ),
        migrations.AddField(
            model_name='event',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 1, 31, 17, 30, 59, 484826, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='ministry',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 1, 31, 17, 31, 50, 292874, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ministry',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='ministry',
            name='order',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='ministry',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='sermon',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 1, 31, 17, 32, 4, 212988, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sermon',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='serviceschedule',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='serviceschedule',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='email',
            field=models.EmailField(db_index=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='is_read',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='name',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='ministry',
            name='title',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='sermon',
            name='category',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sermon',
            name='date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='sermon',
            name='series',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='sermon',
            name='speaker',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sermon',
            name='title',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='serviceschedule',
            name='day',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='serviceschedule',
            name='time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='serviceschedule',
            name='type',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AddIndex(
            model_name='contactmessage',
            index=models.Index(fields=['-created_at', 'is_read'], name='api_contact_created_2b91b5_idx'),
        ),
        migrations.AddIndex(
            model_name='contactmessage',
            index=models.Index(fields=['email', '-created_at'], name='api_contact_email_b204f2_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['-date', 'category'], name='api_event_date_027267_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['title'], name='api_event_title_94d3ca_idx'),
        ),
        migrations.AddIndex(
            model_name='sermon',
            index=models.Index(fields=['-date', 'speaker'], name='api_sermon_date_84ebc7_idx'),
        ),
        migrations.AddIndex(
            model_name='sermon',
            index=models.Index(fields=['series', '-date'], name='api_sermon_series_9a982b_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceschedule',
            index=models.Index(fields=['day', 'time'], name='api_service_day_70fe89_idx'),
        ),
    ]
