# Generated by Django 6.0.1 on 2026-02-01 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_event_options_alter_ministry_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='time',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sermon',
            name='date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='serviceschedule',
            name='time',
            field=models.CharField(max_length=100),
        ),
    ]
